const datos = {};

const fondosTotales = {
  fondoPrincipal: "media/video/fondo_hogwarts.mp4",
  fondoSalon: "https://images4.alphacoders.com/130/1308100.jpeg",
  fondoPociones: "https://w0.peakpx.com/wallpaper/634/492/HD-wallpaper-what-hogwarts-legacy-s-release-date-is-after-delay-hogwarts-classroom.jpg",
  fondoSombrero: "https://images4.alphacoders.com/122/1226374.png",
  fondoEscaleras: "https://images2.alphacoders.com/112/1128762.jpg",
  fondoClase: "https://images2.alphacoders.com/110/1102643.jpg",
  fondoBoggart: "https://picfiles.alphacoders.com/388/388147.jpg",
  fondoBoggartRiddikulus: "https://images8.alphacoders.com/130/1302539.jpg",
  fondoAnimalPatronus: "https://images3.alphacoders.com/130/1302543.png",
  fondoClaseDefensa: "https://images3.alphacoders.com/130/1308095.jpeg",
  fondoClaseDefensaHechizo: "https://images2.alphacoders.com/122/1221683.jpg",
  fondoDementor: "https://images4.alphacoders.com/110/1103702.png",
  fondoPerfil: "https://images6.alphacoders.com/122/1221684.jpg",
};

const casas = [
  {
    nombre: "Gryffindor",
    cualidades: ["valor", "fuerza", "audacia"],
    linaje: ["Mestizo", "Muggle", "Sangre pura"],
    img: "media/img/gryffindor.png",
  },
  {
    nombre: "Hufflepuff",
    cualidades: ["justicia", "lealtad", "paciencia"],
    linaje: ["Mestizo", "Muggle"],
    img: "media/img/hufflepuff.png",
  },
  {
    nombre: "Ravenclaw",
    cualidades: ["creatividad", "erudición", "inteligencia"],
    linaje: ["Mestizo", "Muggle", "Sangre pura"],
    img: "media/img/ravenclaw.png",
  },
  {
    nombre: "Slytherin",
    cualidades: ["ambicion", "determinacion", "astucia"],
    linaje: ["Sangre pura"],
    img: "media/img/slytherin.png",
  },
];

const clases = {
  transformaciones: {
    nombreClase: "Transformaciones",
    nombreProfesor: "Profesor Kevin Slughorn",
    horario: "Lunes - Miercoles 6am - 8am",
    hechizos: {},
  },
  
  herbologia: {
    nombreClase: "Herbologia",
    nombreProfesor: "Profesor Maria Umbridge",
    horario: "Lunes - Miercoles 8am - 10am",
    hechizos: {},
  },

  pociones: {
    nombreClase: "Pociones",
    nombreProfesor: "Profesor Liliana McGonagall",
    horario: "Lunes - Miercoles 10am - 12am",
    pocionesAprendidas: {},
  },

  encantamientos: {
    nombreClase: "Encantamientos",
    nombreProfesor: "Profesora Jackie",
    horario: "Martes - Jueves 6am - 8am",
    hechizos: {},
  },

  defensaContraLasArtesOscuras: {
    nombreClase: "Defensa contra las artes oscuras",
    nombreProfesor: "Profesor Robinson Snape ",
    horario: "Martes - Jueves 8am - 10am",
    hechizos: {},
  },

  animalesMagicos: {
    nombreClase: "Animales magicos",
    nombreProfesor: "Profesor David Filch",
    horario: "Martes - Jueves 10am - 12am",
    hechizos: {},
  },

  historiaDeMagia: {
    nombreClase: "Historia de la magia",
    nombreProfesor: "Profesor Ronald Sprout",
    horario: "Viernes 8am - 10am",
    hechizos: {},
  },
};

const animalesPatronus = [
  "Oso hormiguero",
  "Caballo alado Abraxan ",
  "Víbora",
  "Albatros",
  "Tejón",
  "Sabueso Basset",
  "Murciélago ",
  "Yegua Torda",
  "Semental Tordo",
  "Beagle",
  "Gato blanco y negro",
  "Oso negro ",
  "Mamba negra",
  "Yegua negra",
  "Semental negro",
  "Cisne negro",
  "Mirlo",
  "Sabueso",
  "Borzoi",
  "Oso pardo",
  "Liebre parda",
  "Búho pardo ",
  "Búfalo ",
  "Ratonero",
  "Gato calicó",
  "Mono capuchino",
  "Guepardo ",
  "Yegua Castaña",
  "Semental Castaño",
  "Perro Chow",
  "Cuervo",
  "Yegua gris moteada",
  "Semental gris moteado",
  "Lebrel escocés",
  "Cierva ",
  "Delfín",
  "Dragón ",
  "Libélula",
  "Yegua Dun",
  "Semental Dun",
  "Águila",
  "Búho real ",
  "Elefante ",
  "Erumpent ",
  "Halcón",
  "Ratón de campo",
  "Salamandra que habita en el fuego ",
  "Zorro",
  "Fox Terrier",
  "Gato jengibre",
  "Azor",
  "Caballo alado Graniano ",
  "Culebra de collar",
  "Búho gris ",
  "Galgo",
  "Ardilla gris",
  "Erizo",
  "Garza ",
  "Hipogrifo ",
  "Colibrí",
  "Husky",
  "Hiena ",
  "Podenco ibicenco",
  "Ímpala ",
  "Perro lobo irlandés",
  "Cobra real ",
  "Martín pescador",
  "Leopardo ",
  "Leopardo hembra ",
  "León ",
  "Leona ",
  "Mochuelo ",
  "Lince ",
  "Urraca",
  "Gato manx",
  "Aguilucho paludéreo",
  "Perro mastín",
  "Visón",
  "Topo",
  "Perro mestizo",
  "Liebre de montaña",
  "Gato nebelung",
  "Terranova",
  "Chotacabras",
  "Occamy ",
  "Gato ocicat",
  "Orangután",
  "Orca ",
  "Órix ",
  "Águila pescadora",
  "Nutria",
  "Pavo real ",
  "Faisán",
  "Yegua pía",
  "Semental pío",
  "Garduña",
  "Oso polar ",
  "Turón",
  "Pitón ",
  "Gato ragdoll",
  "Rata",
  "Serpiente de cascabel",
  "Cuervo ",
  "Ardilla roja",
  "Rinoceronte ",
  "Petirrojo",
  "Rottweiler",
  "Runespoor ",
  "Gato azul ruso",
  "Salamandra",
  "Salmón",
  "Búho de anteojos ",
  "Foca ",
  "Tiburón ",
  "Musaraña",
  "Gato siberiano",
  "Búho nival ",
  "Gorrión",
  "Gavilán",
  "Gato esfinge",
  "San Bernardo",
  "Ciervo macho ",
  "Armiño",
  "Golondrina",
  "Vencejo",
  "Thestral ",
  "Tigre ",
  "Tigresa ",
  "Gato tonquinés",
  "Gato carey",
  "Unicornio ",
  "Topo",
  "Buitre ",
  "Comadreja",
  "Terrier de las tierras altas del oeste",
  "Yegua blanca",
  "Semental blanco",
  "Cisne blanco",
  "Jabalí",
  "Conejo salvaje",
  "Gato montés",
  "Lobo",
  "Ratón de madera",
];

